#!/usr/bin/bash

export PGPASSWORD="1234"


VALUE=`timeout 5 /usr/bin/psql -t -d postgres -h 127.0.0.1 -U postgres -p 5434 -c 'select not pg_is_in_recovery()' 2>/dev/null`
rc=$?

if [ $rc -eq 0 ]
then
    VALUE=`timeout 5 /usr/bin/psql -t -d postgres -h 127.0.0.1 -U postgres -p 5003 -c 'select not pg_is_in_recovery()' 2>/dev/null`
rc=$?
fi

# Check the output. If it is not empty then everything is fine and we return something. Else, we just do not return anything.

if [ $rc -ne 0 ]
then
    /bin/echo -ne "HTTP/1.1 503 Service Unavailable\r\n"
    /bin/echo -ne "Content-Type: Content-Type: text/plain\r\n"
    /bin/echo -ne "\r\n"
    /bin/echo "DB Down"
    /bin/echo -ne "\r\n"
elif [ $VALUE == "f" ]
then
    /bin/echo -ne "HTTP/1.1 206 OK\r\n"
    /bin/echo -ne "Content-Type: Content-Type: text/plain\r\n"
    /bin/echo -ne "\r\n"
    /bin/echo "Standby"
    /bin/echo -ne "\r\n"
elif [ $VALUE == "t" ]
then
    /bin/echo -ne "HTTP/1.1 203 OK\r\n"
    /bin/echo -ne "Content-Type: Content-Type: text/plain\r\n"
    /bin/echo -ne "\r\n"
    /bin/echo "Primary"
    /bin/echo -ne "\r\n"
else
    /bin/echo -ne "HTTP/1.1 503 Service Unavailable\r\n"
    /bin/echo -ne "Content-Type: Content-Type: text/plain\r\n"
    /bin/echo -ne "\r\n"
    /bin/echo "DB Down"
    /bin/echo -ne "\r\n"
fi

